### ISSUE TITLE
include_directed_posts=0

### ISSUE THREAD

**Issue by 33mhz** [pnut-api/api-spec#22]
Not include posts directed (leading mentions) at users I don't follow.

Hard for me to implement without a performance penalty. Have been considering it for months.

**Comment by shawnthroop** [comment]
Personally, I don't know why people would enable this feature. I built a toggle into Prose way back when because I heard John Siracusa talk about including mentions in his Twitter timeline and then get a bunch of divided feedback. At the time I thought it better to include more timeline settings than fewer. 

Personally, I don't have it enabled. It's how I discover new users.

**Comment by 33mhz** [comment]
I don't enable it or appreciate it myself, either. But I know a lot of users consider the posts directed at people they don't know as "spammy". :/ They don't want to see a bunch of posts saying "@-otherguy haha".

**Comment by 33mhz** [comment]
Implemented.

**Comment by shawnthroop** [comment]
@33mhz Awesome, just in time for me to build my settings view controller 😉
