### ISSUE TITLE
Including subscribed user objects in channel responses

### ISSUE THREAD

**Issue by kaiwood** [pnut-api/api-spec#30]
I hope I haven't overlooked something, but:

When calling channel endpoints, like `/users/me/channels/subscribed`, it would be useful to have a (optional) array of subscribers in the response, similar to what I get from `/channels/{channel_id}/subscribers`.

My use case:

I want to render a list of all subscribed channels; and if it's a PM-channel, I want to display the username alongside - without doing an additional request.

When building a list of current chat/PM channels, I can't tell exactly who the recipient is without doing 
If someone messages me first, I can get the value out of  `owner`. But If I initiated the conversation, the only hint is the user id found in `acl.write.user_ids` – but that requires keeping track of the users in the application if I want to map the id to the correct username.

Thoughts?

**Comment by 33mhz** [comment]
I think it might be too much for the server to do in one call; you can currently call up to 200 channels at once. Channels I believe can have up to 200 users in them. So the potential to assemble 200 channels and 40,000 user objects... is crazy.

What I've done is what you're saying; a second call to `/users?ids=...`, with all the visible user IDs, and track a list of IDs so that you don't have to call repeats on later channels. For avatars, you can use `/users/{user_id}/avatar?w={width}` as the URL of the image, if you want. It might be nice to be able to have something like `include_user_as_username=1` on calls...

**Comment by 33mhz** [comment]
There's potential to include usernames, or some sort of "light" profile. Username, ID, something else?

**Comment by kaiwood** [comment]
Yep, for full blown channels with many users in it that would be heavy (on the client side as well, smells like a potential couple of MB to download). I was more thinking of the most common scenario, having a list of current PM conversations and small group chats where one can click/touch to open the conversation.

So light profile would totally do it. Username, ID, plus `user.content.avatar_image.link` for rendering the typical small avatar?

**Comment by 33mhz** [comment]
At least initially, I'll only allow it on `/users/me/channels/subscribed`. Very specific use-case. I may open it to anything in the future, it shouldn't be a problem. But this is my option. :)

It's on the list. This patch or next, I expect it.

**Comment by 33mhz** [comment]
Presumably something like:
```json
"acl":{
  "full":{
    "user_ids":[
      {
        "id": "2",
        "username": "Wife"
      },
      {
        "id": "1",
        "username": "33MHz",
        "name": "Robert"
      }
    ]
  }
}
```
Skeptical of adding avatar, since you can simply use the /users/{user_id}/avatar endpoint.

**Comment by 33mhz** [comment]
Pushed.
