### ISSUE TITLE
[Request] File versioning

### ISSUE THREAD

**Issue by hutattedonmyarm** [pnut-api/api-spec#36]
The link stays the same, which isn’t the case when deleting/re-uploading a file. I want to build an overview over the clients and their supported features. Being able to update files means I can share/link to it once and don’t have to update it every time it changes. My plan was to do it as markdown formatted file instead of hosting it as website.

It could be a relatively simple implementation, e.g. adding a ‚version‘ field to the file object and the ability to update a file

**Comment by 33mhz** [comment]
For the purposes of file storage, being able to version a file in place seems really helpful.
The problem with being able to update a file without changing the link seems like the same problem as allowing people to change post entities when revising a post.

E.g., a post might have an oEmbed pointed to a pnut file. A person reposts that post, and the person changes the file, changing what another person reposted. In theory, a person could link to somewhere else and then change what that link is pointing to, but it seems crummy to allow within the pnut API.

Because of this kind of gaming or unexpected behavior, post raw is immutable, except the oembed links themselves, which are updated on demand for convenience, without affecting content.

Just thinking out loud, versioning a file could *not* delete the old file, and file revisions would be like post threads; related to each other, but not automatically deleted. You would be able to pull up the "latest" file easily.

**Comment by 33mhz** [comment]
Or it could be that files could only be revised *if* they were not oEmbedded.

**Comment by 33mhz** [comment]
May revisit this in the future, but have no plans for it.
