### ISSUE TITLE
[Request] Serverside Hashtag muting

### ISSUE THREAD

**Issue by hutattedonmyarm** [pnut-api/api-spec#38]
It can be done as a client feature, but doing it serverside has a few advantages:

* Cross platform. Mute in one client on the phone, have a quiet life on the computer
* (Slight) performance increase. Clientside means fetching and transmitting all posts, then filter. Serverside filtering saves data as the filtered posts won’t even be transmitted

It’s absolutely not a priority though

**Comment by 33mhz** [comment]
It might be doable in posts. Would require:
* `PUT /posts/tags/{tag}/mute`
* `DELETE /posts/tags/{tag}/mute`
* `GET /users/me/tags/muted`
* backend work to filter them out

**Comment by 33mhz** [comment]
### Expiration
People also are interested in tag muting for a certain period of time.

### NSFW
If we're muting tags, we could stop handling NSFW specially.

### Justification
All clients would benefit from native tag muting, like NSFW and user muting/blocking.

### Cons
Besides the performance hit, there's a good chance people muting a tag would still want to be informed that the post exists in their thread/stream, as it could otherwise leave holes in their conversations unintentionally. E.g., someone replies to you with a tag you happen to have muted, and now you don't see their reply. That's desirable with user-muting, but tag muting tends to be more casual than "I don't want to ever be exposed to posts involving the NFL" or something.

I'll keep considering it, but won't put it on the roadmap at this point.

**Comment by hutattedonmyarm** [comment]
> there's a good chance people muting a tag would still want to be informed that the post exists in their thread/stream as it could otherwise leave holes in their conversations unintentionally

Suggestion: Don't show it in the timeline/other streams at all, and show some kind of placeholder when viewing a thread. Could also be a parameter like include_deleted. Basically, streams having include_muted_tags default to 0, and threads having it default to 1

> someone replies to you with a tag you happen to have muted, and now you don't see their reply

I'd *always* show posts mentioning the user regardless of muted tags

**Comment by 33mhz** [comment]
That's not a bad design, but it is opinionated. Currently it's pretty easy for a client to mute tags, so I'm going to put this along with things like "hide reposts from user X". :)

**Comment by 33mhz** [comment]
We may revisit this some time in the future, but I'm not considering it now.
