### ISSUE TITLE
Password Flow skips MFA

### ISSUE THREAD

**Issue by DaveWoodCom** [pnut-api/api-spec#53]
I'm guessing this is to do with the Password Flow option, but could be wrong.

When logging in with a user account that has MFA enabled in an app that uses Password Flow, the user is authenticated without providing an MFA code.

I encountered this when logging in with my account (when MFA was enabled) with the Robin Android client.

**Comment by 33mhz** [comment]
This is so far intentional. Clients are unaware of MFA requirements for an account.

**Comment by DaveWoodCom** [comment]
I would suggest making a slight change to the way passwords etc are handled.

I'd change things so that if MFA is enabled on an account, the users main password will not let them log into third party apps. It will only let them log into the main pnut.io web site, along with an MFA code of course.

Then users must use a one-time password to log into any third party app. That one time password would have required the MFA code in order to be created (i.e., when the logged into the web site). Since the one time password needed a MFA code to be created, an MFA code shouldn't be required to use that password to log in.

I think that will simply the log in process without compromising security. It'll also allow you to let more third party apps use the password flow since the password can't ever be reused. A side effect is that this will fix client issues that exist right now where you can't log into Apero for example when MFA is enabled #48.

Extra thought: Perhaps request a new MFA code on the site when generating a one time password if the use hasn't entered one recently, i.e. they had a saved login etc.

**Comment by 33mhz** [comment]
These are some great ideas.

The only things this improves for end users is 1) force MFA users to use OTP when they might otherwise not and 2) disallow brute forcing MFA users through password flow. For MFA users with good passwords, brute forcing is a nigh impossible task, with rate limiting, not to mention users always get an Email from password flow allowance, and email scope not being allowed over password flow... a successful hacker (who is also a pnut.io client developer!) could read your PMs and post as you, and not without your notice.

Apero doesn't use password flow. How would this change affect it?

I like that this does bottle up password flow for MFA users. It isn't an easily explained process, as many users won't realize whether they're using password flow or not, and so when they have to use an OTP, etc.. Thankfully, there are probably very few people logging into password-flow clients with MFA enabled. But explaining could confuse people who aren't using it.

On the balance, I'd prefer to implement what you're suggesting. I'll think about how the UI and language would work while I finish reworking the site cookie handling.

**Comment by 33mhz** [comment]
I might "Require OTP for password flow" as a secondary option. Then people who read things might enable it, and people who don't won't be stuck outside their client with no explanation but that their user/password is somehow wrong.
